CREATE TABLE MARKS(
    REGNO VARCHAR(9),
    NAME VARCHAR(25) NOT NULL,
    CAT1 DECIMAL (2,2) DEFAULT 00.00,
    CAT2 DECIMAL (2,2) DEFAULT 00.00,
    FAT DECIMAL (3,2) DEFAULT 000.00,
    PRIMARY KEY (REGNO)
);

ALTER TABLE MARKS 
    ADD CONSTRAINT CHK_MARKS CHECK(CAT1<=50.00 AND CAT2<=50.00 AND FAT<=100.00);

ALTER TABLE `marks` CHANGE `CAT1` `CAT1` DOUBLE(2,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `CAT2` `CAT2` DOUBLE(2,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `FAT` `FAT` DOUBLE(3,2) NULL DEFAULT '0.00';

ALTER TABLE `marks` CHANGE `CAT1` `CAT1` NUMERIC(2,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `CAT2` `CAT2` NUMERIC(2,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `FAT` `FAT` NUMERIC(3,2) NULL DEFAULT '0.00';

ALTER TABLE `marks` CHANGE `CAT1` `CAT1` NUMERIC(4,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `CAT2` `CAT2` NUMERIC(4,2) NULL DEFAULT '0.00';
ALTER TABLE `marks` CHANGE `FAT` `FAT` NUMERIC(5,2) NULL DEFAULT '0.00';

CREATE TABLE users(
   user_id INT AUTO_INCREMENT PRIMARY KEY,
   username VARCHAR(40) NOT NULL UNIQUE,
   password VARCHAR(255) NOT NULL
);